apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: koh-kojima-pipeline-from-scratch
commonAnnotations:
  enzo: "true"
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: koh-kojima-express-app
  app.kubernetes.io/instance: koh-kojima-pipeline-from-scratch
  app.kubernetes.io/name: koh-kojima-express-app
